#
title: USM COS 470 Mobile Application Development (Spring 2020)
theme: minima
excerpt_separator: <!--more-->
github_username: usm-cos470-s20
twitter_username: stephenhouser
author: Stephen Houser
email: houser@maine.edu
description: University of Southern Maine, Computer Science
timezone: America/New York

collections:
  notes:
    output: true
    sort_by: order
  projects:
    output: true
    sort_by: order
  samples:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"
      hidden: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      hidden: false
  - scope:
      path: ""
      type: "samples"
    values:
      layout: "sample"
      hidden: false

# Where things are
#source:       .
#destination:  ./_site
#plugins_dir:  _plugins
#layouts_dir:  _layouts
#data_dir:     _data
#includes_dir: _includes
#collections:
#  posts:
#    output:   true

# Handling Reading
#safe:                 false
#include:              [".htaccess"]
exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "TODO.md"]
#keep_files:           [".git", ".svn"]
#encoding:             "utf-8"
#markdown_ext:         "markdown,mkdown,mkdn,mkd,md"
#strict_front_matter: false

# Filtering Content
#show_drafts: null
#limit_posts: 0
#future:      false
#unpublished: false

# Plugins
#whitelist: []
#plugins:   []

# Conversion
#markdown:    kramdown
#highlighter: rouge
#lsi:         false
#excerpt_separator: "\n\n"
#incremental: false

# Serving
#detach:  false
#port:    4000
#host:    127.0.0.1
#baseurl: "" # does not include hostname
#show_dir_listing: false

# Outputting
#permalink:     date
#paginate_path: /page:num
#timezone:      null

#quiet:    false
#verbose:  false
#defaults: []
#
#liquid:
#  error_mode: warn

# Markdown Processors
#rdiscount:
#  extensions: []
#
#redcarpet:
#  extensions: []
#
#kramdown:
#  auto_ids:       true
#  entity_output:  as_char
#  toc_levels:     1..6
#  smart_quotes:   lsquo,rsquo,ldquo,rdquo
#  input:          GFM
#  hard_wrap:      false
#  footnote_nr:    1